const ROLES = Object.freeze({
  USER: 'user',
  ADMIN: 'admin',
});

const AUTH_PROVIDERS = Object.freeze({
  LOCAL: 'local',
  GOOGLE: 'google',
  FACEBOOK: 'facebook',
});

const ACTIVITY_ACTIONS = Object.freeze({
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  OAUTH_LOGIN: 'OAUTH_LOGIN',
  LOGOUT: 'LOGOUT',
  POST_CREATE: 'POST_CREATE',
  POST_UPDATE: 'POST_UPDATE',
  POST_DELETE: 'POST_DELETE',
  POST_RESTORE: 'POST_RESTORE',
  COMMENT_CREATE: 'COMMENT_CREATE',
  COMMENT_UPDATE: 'COMMENT_UPDATE',
  COMMENT_DELETE: 'COMMENT_DELETE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
});

const REFRESH_COOKIE_NAME = 'refreshToken';

module.exports = { ROLES, AUTH_PROVIDERS, ACTIVITY_ACTIONS, REFRESH_COOKIE_NAME };
